# Project information
site_name: "Awesome Trend Community"
site_url: "https://github.com/mawinkler/trend-community"
site_description: "A curated list of awesome Trend Community resources for improving your experience with Trend solutions"
site_author: "Markus Winkler"
copyright: "Copyright 2020 - Markus Winkler. Creative Commons Zero v1.0 Universal."

# Repository
repo_name: "trend-community"
repo_url: "https://github.com/mawinkler/trend-community"
edit_uri: ""

# Theme configuration
theme:
  name: "material"
  logo: "https://github.com/mawinkler/trend-community/images/icon.svg"
  icon: "https://github.com/mawinkler/trend-community/images/icon.svg"
  language: "en"
  palette:
    primary: "light-blue"
    accent: "pink"
  feature:
    tabs: false
extra_css:
  - css/extra.css

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/mawinkler"
    - type: "twitter"
      link: "https://twitter.com/mawinkler"
    - type: "linkedin"
      link: "https://www.linkedin.com/in/markus-winkler-785baa34/"

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists

# The pages to serve
nav:
  - "The Awesome List": "index.md"
  - "Contributing": "contributing.md"
  - "Code of Conduct": "code-of-conduct.md"
  - "License": "license.md"
